name: Java CI with Maven

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sen2vm/sen2vm-build-env:0.1.0
    steps:
    - uses: actions/checkout@v4
    - name: Build with Maven
      run: mvn -B -U -f pom.xml install
    - name: Artifact deployment
      run: mvn -B -U -f pom.xml deploy -Dmaven.repository.target=${{ github.repository }}
      env:
        MAVEN_USERNAME: ${{ secrets.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
