name: Java CI with Maven

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sen2vm/sen2vm-build-env:0.1.0
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: mvn -B -U -f pom.xml install
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/') && ( github.ref == 'refs/heads/main' )
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            mvn -B -U -f pom.xml \
                -s .CI/maven-settings.xml \
                deploy -DskipTests=true \
                -Dmaven.repository.target=${{ github.repository }}
          else
            echo "Tag '$TAG_NAME' does not follow SemVer format. No artifact released."
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
